node-installer: refactor the "curl" test to Makefile targets for integration tests
Signed-off-by: Jiaxiao (mossaka) Zhou <duibao55328@gmail.com>

diff --git a/node-installer/Makefile b/node-installer/Makefile
--- a/node-installer/Makefile
+++ b/node-installer/Makefile
@@ -1,5 +1,6 @@
 SPIN_VERSION = v2
 IMAGE_NAME ?= ghcr.io/spinkube/containerd-shim-spin/node-installer
+KUBECTL ?= kubectl
 
 # we only support x86_64 and aarch64 on Linux
 UNAME := $(shell uname -m)
@@ -32,6 +33,27 @@ build-multi-installer-image: $(BINARY)
 
 build-dev-installer-image: $(BINARY)
 	docker buildx build -t $(IMAGE_NAME) --load --platform $(PLATFORM) .
+
+deploy-workload:
+	$(KUBECTL) apply -f ./tests/workloads/workload.yaml
+	$(KUBECTL) wait --for=condition=Available deployment/wasm-spin --timeout=120s
+	$(KUBECTL) get pods
+
+test-workload:
+	@sleep 10
+	$(eval PID := $(shell $(KUBECTL) port-forward svc/wasm-spin 8888:80 > /dev/null 2>&1 & echo $$!))
+	@sleep 5
+	@for i in $$(seq 1 3); do \
+		if curl -s http://localhost:8888/hello | grep -q "Hello world from Spin!"; then \
+			kill $(PID) 2>/dev/null || true; \
+			exit 0; \
+		else \
+			sleep 3; \
+		fi; \
+	done; \
+	kill $(PID) 2>/dev/null || true; \
+	echo "Failed to get a successful response from the workload."
+	exit 1
 
 test-kind:
 	./tests/integration-test-kind.sh
